### ISSUE TITLE
Подмена данных

### ISSUE THREAD

**Issue by alexmikhalevich** [FRTP/Framework#13]
Возможность загрузки данных на сервер открывает возможность подмены информации, если знать точное имя файла. Пока эта проблема не будет решена, нельзя предоставлять публичный доступ к информации.  
Кажется, что самое простое решение - механизм авторизации.

**Comment by alexmikhalevich** [comment]
В качестве альтернативы механизму авторизации можно реализовать файловые операции используя не имена, а некие хеши, уникальные для каждого файла. Правда, это будет медленнее.

**Comment by pershik** [comment]
Я за авторизацию. Даже если убрать возможность подмены файлов, левые люди могут залить на сервер 10Тб /dev/random'a, чего не хотелось бы допускать.

Нужно мнение @alexpodkin

**Comment by ghost** [comment]
+ за авторизацию

**Comment by alexmikhalevich** [comment]
#19
